# Generated by Django 3.0.7 on 2020-07-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipios', '0003_auto_20200704_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
