# Generated by Django 3.0.7 on 2020-07-05 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipios', '0004_auto_20200704_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipio',
            name='id',
        ),
        migrations.AlterField(
            model_name='municipio',
            name='cod_municipio',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
