# Generated by Django 3.0.7 on 2020-07-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paises', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pais',
            name='id',
        ),
        migrations.AlterField(
            model_name='pais',
            name='cod_pais',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
