# Generated by Django 2.2.12 on 2020-07-06 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('municipios', '0005_auto_20200705_0024'),
        ('paises', '0002_auto_20200704_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('estu_tipodocumento', models.CharField(max_length=10)),
                ('genero', models.CharField(max_length=5)),
                ('edad', models.SmallIntegerField()),
                ('periodo', models.SmallIntegerField()),
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('tiene_etnia', models.CharField(blank=True, max_length=5, null=True)),
                ('etnia', models.CharField(blank=True, max_length=100, null=True)),
                ('priv_libertad', models.CharField(blank=True, max_length=5, null=True)),
                ('inse', models.FloatField()),
                ('nse', models.SmallIntegerField(blank=True, null=True)),
                ('cod_municipio_reside', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='municipios.Municipio')),
                ('cod_paisnacionalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paises.Pais')),
            ],
        ),
    ]
