# Generated by Django 3.0.7 on 2020-07-04 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('municipios', '0004_auto_20200704_1612'),
        ('departamentos', '0003_auto_20200704_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colegios',
            fields=[
                ('cod_colegio', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('cod_dane', models.BigIntegerField(blank=True)),
                ('nombre', models.CharField(max_length=200)),
                ('genero', models.CharField(max_length=10)),
                ('naturaleza', models.CharField(blank=True, max_length=15)),
                ('calendario', models.CharField(max_length=10)),
                ('bilingue', models.CharField(blank=True, max_length=10, null=True)),
                ('caracter', models.CharField(blank=True, max_length=20, null=True)),
                ('cod_dane_sede', models.BigIntegerField(blank=True)),
                ('nombre_sede', models.CharField(max_length=200)),
                ('sede_principal', models.CharField(blank=True, max_length=10)),
                ('area_ubicacion', models.CharField(blank=True, max_length=20)),
                ('jornada', models.CharField(blank=True, max_length=20)),
                ('cod_departamento_ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamentos.Departamento')),
                ('cod_municipio_ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='municipios.Municipio')),
            ],
        ),
    ]
