# Generated by Django 3.0.7 on 2020-07-05 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colegios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colegios',
            name='cod_departamento_ubicacion',
        ),
        migrations.RemoveField(
            model_name='colegios',
            name='cod_municipio_ubicacion',
        ),
    ]
