# Generated by Django 3.0.7 on 2020-07-05 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colegios', '0002_auto_20200705_0043'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Colegios',
        ),
    ]
