# Generated by Django 3.0.7 on 2020-07-03 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('cod_departmento', models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='departamentos',
        ),
    ]
