# Generated by Django 3.0.7 on 2020-07-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0002_auto_20200703_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='id',
        ),
        migrations.AlterField(
            model_name='departamento',
            name='cod_departmento',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
